#!/usr/bin/env python3
"""Compile assets/art/manifest.json into C tables.

Same reasoning as the game data: generating C keeps a parser out of the
runtime and makes the asset set visible in a diff.

    python3 tools/gen_asset_manifest.py
"""
import argparse
import hashlib
import json
import re
import os

NUMBER_LOOKUP = '\nconst NumberAnim *number_anim(const char *name)\n{\n    if (!name)\n        return NULL;\n    for (int i = 0; i < SONNY_NUMBER_ANIM_COUNT; i++)\n        if (strcmp(SONNY_NUMBER_ANIMS[i].name, name) == 0)\n            return &SONNY_NUMBER_ANIMS[i];\n    return NULL;\n}'

HEADER = '''/* GENERATED by tools/gen_asset_manifest.py -- do not edit. */
#ifndef SONNY_ASSETS_GEN_H
#define SONNY_ASSETS_GEN_H

#include <stdint.h>

/* One named asset: a still has a single frame, an animation has several, in
   order. Paths are relative to the repository root. */
/* Where a frame's own origin sits inside its exported image. Drawing the
   image with its top-left at (target - offset) puts the art exactly where the
   game draws it; without this, trimmed and padded exports land beside their
   mark. */
typedef struct {
    float x, y;
} AssetOffset;

typedef struct {
    const char        *name;
    const char        *category;
    const char *const *frames;
    const AssetOffset *offsets;   /* NULL when unknown */
    int32_t            frame_count;
    /* How many pixels of this asset's image there are to the stage unit. The
       decompiler exports at one; art rasterised from the vector source is
       finer than that, and every draw divides by this to get back to the
       units everything else is in. */
    float              scale;
    /* Where this art sits relative to its parent's origin, when known: the
       shape's bounds with its placement matrix applied. has_bounds is 0 for
       assets whose position the engine supplies instead. */
    int32_t            has_bounds;
    float              xmin, ymin, xmax, ymax;
} AssetEntry;

/* An animation state of the character model, as its frame labels define it.
   Frames are 1-based indices into the model's own frame list. */
typedef struct {
    const char *name;
    int32_t     start;
    int32_t     end;
    int32_t     length;
} AssetAnimation;

/* One part of the character model on one frame: the instance name and the
   matrix the model's timeline gives it. Matrices are SWF form --
   x' = a*x + c*y + tx, y' = b*x + d*y + ty -- with translation in pixels. */
typedef struct {
    const char *part;
    float       a, b, c, d, tx, ty;
    /* What sits in the slot. Body parts are dressed from the character's own
       equipment and ignore this; the model's one unnamed slot swaps whole
       effect clips through it, and there this is the only way to tell which. */
    int32_t     character;
    /* How opaque this one slot is on this frame. The body parts are always
       solid, but the effect slot is animated entirely through this: the cast
       orb swells in over three frames, holds, and is faded to nothing over
       the rest of the animation. */
    float       alpha;
} DollPlacement;

typedef struct {
    const DollPlacement *parts;
    int32_t              count;
    /* How opaque the whole model is on this frame. It is 1 everywhere but the
       last eleven frames of the death animation, which fade it out. */
    float                alpha;
} DollFrame;

/* How a doll part maps to equipment: `core` indexes the 7 equipment slots and
   `art` is the name used in the export ("M_<art>_<look>"). */
typedef struct {
    const char *part;
    int32_t     core;
    const char *art;
} DollPart;

/* One layer of an effect the model plays over itself, on one of that effect's
   own frames. The model keeps a single slot for these and swaps the clip in
   it: a sweep through the magic swing, the orb a caster charges, the crackle
   of being held stunned. `tinted` marks the layer the game recolours to the
   move's own colour with Color.setRGB; the other layer of each pair keeps the
   colour it was drawn in. Matrices are SWF form, inside the effect clip. */
typedef struct {
    int32_t character;
    float   a, b, c, d, tx, ty;
    float   alpha;
    int32_t tinted;
} CastLayer;

typedef struct {
    const CastLayer *layers;
    int32_t          count;
} CastFrame;

/* The effect belonging to one model animation, by that animation's name. */
typedef struct {
    const char      *animation;
    int32_t          character;
    const CastFrame *frames;
    int32_t          count;
    int32_t          loops;   /* 0 stops on its last frame, 1 runs round */
} CastEffect;

/* Where the battle screen stands each unit, in stage coordinates, straight
   out of the original's own display list. The right-hand team's containers
   carry a negative horizontal scale, which is how the game mirrors them. */
typedef struct {
    int32_t slot;
    float   x, y;
    float   scale_x, scale_y;
    int32_t flip;
} StageSlot;

/* Where the health and focus bar for a slot sits, straight off the root
   timeline (p1BAR..p6BAR), with the bar art's own size. */
typedef struct {
    int32_t slot;
    float   x, y;          /* where the bar is placed */
    float   scale;         /* horizontal; the original's is not uniform */
    float   scale_y;
    float   width, height; /* the bar art's size */
    float   origin_x, origin_y;  /* where its own origin sits inside it */
} StageBar;

/* One piece of the battle screen's furniture, as the root timeline places it
   on the KRINBATTLESCENE frame: the top stats panel, the black battlefield
   backing, the three panels along the bottom, the turn indicator. `name` is
   the instance name where the original gave it one and "@<depth>" where it
   did not, and `depth` is the stacking order the original draws them in. The
   art is asset "#<character>", whose exported canvas is width x height with
   the piece's own origin at (origin_x, origin_y) inside it. */
typedef struct {
    const char *screen;    /* the root frame that places it */
    const char *name;
    int32_t     depth;
    int32_t     character;
    /* Non-zero when the placement is a mask rather than a picture: it clips
       everything above it up to this depth. The battle screen has one, which
       is what keeps the backdrop inside the battlefield frame. */
    int32_t     clip_depth;
    float       x, y;
    float       scale_x, scale_y;
    float       width, height;
    float       origin_x, origin_y;
} StageChrome;

/* One piece of the health/focus bar widget, in the bar's own coordinates.
   The parts in depth order are the black panel, the two fills, and a
   translucent gloss over them; the fills are drawn to a fraction of their
   width, which is how the bar shows a value. */
typedef struct {
    const char *name;
    int32_t     character;
    int32_t     depth;
    int32_t     clip_depth;   /* non-zero when the part is a mask */
    float       x, y;
    float       scale_x, scale_y;
    float       width, height;
    float       origin_x, origin_y;
} BarPart;

/* One of the bar's text fields, also in the bar's own coordinates. `side` is
   "left" or "right": the right-hand team's bars mirror the widget, and the
   original does that by running the text on its own second layout. `align` is
   the SWF's: 0 left, 1 right, 2 centre. `device` marks a field set in one of
   Flash's device fonts ("_sans"), which the player renders with a system face
   rather than with anything embedded in the file. */
typedef struct {
    const char *side;
    const char *role;      /* name, lifeNow, lifeMax, focusNow, focusMax */
    float       x, y;
    float       width, height;
    float       size;
    float       leading;   /* the gap the player leaves above the line */
    int32_t     align;
    int32_t     device;
    unsigned char r, g, b;
} BarField;

/* One of the eight orbs in the ability ring, in the ring's own coordinates.
   The player does not choose a move from a bar: hovering a unit brings up this
   ring around it, one orb per slot of the loadout, and clicking an orb uses
   that ability on that unit. */
typedef struct {
    int32_t slot;
    float   x, y;
    float   scale_x, scale_y;
} RingSlot;

/* A piece of the orb. It is built rather than drawn whole, because the clip's
   labelled frames have the black "cannot use this" disc in front of
   everything: a ball, the icon over it, a glass highlight, and that disc only
   when the ability is unusable. The icon is asset "<icon name>" in the orb
   category; `art` here is the shared piece, asset "#<character>". */
typedef struct {
    const char *role;      /* ball, mask, glass, filter */
    int32_t     character;
    int32_t     depth;
    float       x, y;
    float       scale_x, scale_y;
    float       width, height;
    float       origin_x, origin_y;
} OrbPart;

/* The floating number a hit puts over its target. It is not text: the game
   attaches one digit clip per digit into NumberFixer's `flasher` and plays
   one of that clip's four labelled sections. A section is a run of frames,
   each of which says what `flasher` is scaled to, how far it has risen and
   how opaque it is -- which is the punch, the lift and the fade. */
typedef struct {
    float scale;
    float y;
    float alpha;
} NumberFrame;

/* A piece of a digit, or of the words "miss" and "shield": their own art,
   placed inside the clip that holds them. `tinted` marks the one the game
   recolours to the element the hit was -- the instance the original calls KN,
   which is the glyph itself; the backing and the gloss over it keep the
   colour they were drawn in. */
typedef struct {
    const char *art;
    float       x, y;
    float       scale;
    float       origin_x, origin_y;
    int32_t     tinted;
} NumberPart;

typedef struct {
    const char        *name;     /* normal, critical, miss, shield */
    const NumberFrame *frames;
    int32_t            count;
    /* What `flasher` holds on those frames: the two words carry their own
       art, a number has none and is the digits. */
    const NumberPart  *parts;
    int32_t            part_count;
} NumberAnim;

typedef struct {
    const NumberPart *parts;
    int32_t           count;
} NumberDigit;

/* One drawable piece of a clip, in that clip's own coordinates. A clip that
   carries text fields cannot be exported whole -- the decompiler bakes the
   fields' design-time copy into the picture -- so its graphics are taken
   apart and the text drawn over them. `frames` is non-zero for a piece the
   game points at a frame of by name, like the speech box's portrait: its art
   is then the asset of that name rather than "#<character>". */
typedef struct {
    const char *screen;
    const char *owner;
    const char *name;
    int32_t     character;
    int32_t     depth;
    int32_t     frames;
    float       x, y;
    float       scale_x, scale_y;
    float       width, height;
    float       origin_x, origin_y;
} ClipPart;

/* One text field of the battle screen's furniture, in stage coordinates,
   straight off the DefineEditText tag: its box, the size and colour it is set
   in, its alignment (0 left, 1 right, 2 centre), the leading the player puts
   above the first line, and whether it uses one of Flash's device fonts.
   `owner` is the instance it belongs to, so the fields of something the game
   moves around -- a target's reticle, the speech box -- are taken relative to
   where that instance is placed. */
typedef struct {
    const char *screen;    /* the root frame that places its owner */
    const char *owner;     /* which clip it belongs to */
    const char *name;      /* the instance name inside that clip */
    const char *variable;  /* the variable the frame's script sets */
    /* What the frame authored into the field. A field with no variable is
       never set at run time, so this is the text the screen shows -- as the
       HTML it was authored with. */
    const char *text;
    float       x, y;
    float       width, height;
    float       size;
    float       leading;
    int32_t     align;
    int32_t     device;
    unsigned char r, g, b;
} TextField;

/* The two backdrop layers, which are containers rather than pictures: the
   game points each at the zone's own art on load, the sky with
   gotoAndStop(Krin.SkyBG) and the ground with gotoAndStop(Krin.ZoneBG). */
typedef struct {
    const char *name;      /* "sky" or "zone" */
    float       x, y;
    float       scale_x, scale_y;
} StageLayer;

/* A button a screen places, with the box it responds in, in stage
   coordinates. A button is not a sprite -- it never appears in the art -- so
   its character id is what says what pressing it does. */
typedef struct {
    const char *screen;    /* the root frame that places it */
    const char *owner;     /* the clip it sits in */
    const char *name;      /* the instance name inside that clip */
    int32_t     character;
    float       x, y, width, height;
    /* What the screen shrank or grew the button to. A button's own art is
       recorded at its own size, so this is what puts it where the button
       actually is. */
    float       scale_x, scale_y;
} StageButton;

/* One piece of a button's resting art. A button is not a sprite and its art
   is nowhere else in the file, so a screen whose furniture is a row of
   buttons -- the plus signs beside the attributes -- draws them from here.
   `art` is asset "#<character>". */
typedef struct {
    int32_t button;        /* the button's own character id */
    int32_t character;
    int32_t up;            /* shows at rest */
    int32_t over;          /* shows under the pointer */
    float   x, y;
    float   scale_x, scale_y;
    float   width, height;
    float   origin_x, origin_y;
} ButtonPiece;

extern const ButtonPiece SONNY_BUTTON_ART[];
extern const int SONNY_BUTTON_ART_COUNT;
/* The `index`-th piece of this button's art, bottom up. */
const ButtonPiece *button_piece(int32_t button, int32_t index);

extern const StageButton SONNY_BUTTONS[];
extern const int SONNY_BUTTON_COUNT;
/* The `index`-th button on `screen` with this character, in placement order. */
const StageButton *stage_button(const char *screen, int32_t character,
                                int32_t index);

/* The scene the hub is built around: one clip with a frame per zone, drawn as
   asset "<label>" in the zone category, and the markers on it the player
   clicks to pick a fight. */
typedef struct {
    const char *zone;      /* the frame's label, which is the art's name */
    const char *style;     /* the art, one per colour the scenes ask for */
    float       x, y;      /* where it stands, inside the scene */
    float       scale_x, scale_y;
} ZoneMarker;

extern const ZoneMarker SONNY_ZONE_MARKERS[];
extern const int SONNY_ZONE_MARKER_COUNT;
/* The `index`-th marker on `zone`, in the order the frame stacks them. */
const ZoneMarker *zone_marker(const char *zone, int32_t index);
/* How many frames the marker turns through, and how fast. The SWF runs at 30
   frames a second and the clip is its own loop. */
extern const int SONNY_MARKER_FRAMES;
extern const float SONNY_MARKER_FPS;
/* One zone's marker on the world map, in stage coordinates, with the box it
   answers in. The map shows a marker once the player has reached the zone it
   leads to, and draws its own lines between the ones that show. */
typedef struct {
    int32_t zone;
    int32_t character;
    float   x, y;
    float   width, height;
} MapMarker;

extern const MapMarker SONNY_MAP_MARKERS[];
extern const int SONNY_MAP_MARKER_COUNT;

/* Where the scene is placed, and which frame label each zone uses. */
extern const StageLayer SONNY_ZONE_SCREEN;
extern const char *const SONNY_ZONE_LABELS[];
extern const int SONNY_ZONE_LABEL_COUNT;

/* Where a talent tree node sits on the stage. */
typedef struct {
    int32_t node;
    float   x, y;
    float   scale;
} TalentSlot;

/* A named slot on one of the menu screens, in stage coordinates: the bag
   slots, the equipment slots, the drop slots, the doll preview. `menu` is the
   frame of the menu clip it belongs to -- inventory, win, shop, skills -- and
   the same name means different places on different frames. */
typedef struct {
    const char *menu;
    const char *name;
    float       x, y;
    float       scale;
    /* Where the slot sits in its menu frame's stack, so a screen that draws
       that frame's graphics itself can put the slot back among them. */
    int32_t     depth;
    /* The slot's own clip, whose resting frame is the empty square. */
    int32_t     character;
    float       width, height;
    float       origin_x, origin_y;
} MenuSlot;

/* A named piece inside a slot: the eight bars in each of the piercing and
   defense bands are these, one per element, sized and coloured by the
   character's own numbers. */
typedef struct {
    const char *menu;
    const char *slot;
    const char *name;
    int32_t     character;
    float       x, y;
    float       scale_x, scale_y;
    float       width, height;
    float       origin_x, origin_y;
} SlotPiece;

extern const SlotPiece SONNY_SLOT_PIECES[];
extern const int SONNY_SLOT_PIECE_COUNT;
/* The `index`-th piece of `slot` on `menu`, in the order it stacks them. */
const SlotPiece *slot_piece(const char *menu, const char *slot, int32_t index);

extern const MenuSlot SONNY_MENU_SLOTS[];
extern const int SONNY_MENU_SLOT_COUNT;
const MenuSlot *menu_slot(const char *menu, const char *name);

extern const TalentSlot SONNY_TALENT_SLOTS[];
extern const int SONNY_TALENT_SLOT_COUNT;
const TalentSlot *talent_slot(int32_t node);

extern const NumberAnim SONNY_NUMBER_ANIMS[];
extern const int SONNY_NUMBER_ANIM_COUNT;
/* The four sections by name; NULL when absent. */
const NumberAnim *number_anim(const char *name);
extern const NumberDigit SONNY_NUMBER_DIGITS[10];
/* numberSpacingKrin: how far apart the digits of one number stand. */
extern const float SONNY_NUMBER_SPACING;

extern const ClipPart SONNY_CLIP_PARTS[];
extern const int SONNY_CLIP_PART_COUNT;
/* The `index`-th piece of `owner` on `screen`, in the order it stacks them. */
const ClipPart *clip_part(const char *screen, const char *owner,
                          int32_t index);

extern const TextField SONNY_TEXT_FIELDS[];
extern const int SONNY_TEXT_FIELD_COUNT;
/* The `index`-th field of `owner`, in the order the clip stacks them. */
const TextField *text_field(const char *screen, const char *owner,
                            int32_t index);
/* The `occurrence`-th field called `name`. A screen repeats a name where it
   repeats a row -- one per party member, say. */
const TextField *text_field_named(const char *screen, const char *owner,
                                  const char *name, int32_t occurrence);
/* The field bound to this variable. A frame's script fills its screen by
   setting variables, so this is what says which field shows what. */
const TextField *text_field_var(const char *screen, const char *variable);

extern const RingSlot SONNY_RING_SLOTS[];
extern const int SONNY_RING_SLOT_COUNT;
/* The ring's own scale, which the orbs' offsets are in. */
extern const float SONNY_RING_SCALE;

extern const OrbPart SONNY_ORB_PARTS[];
extern const int SONNY_ORB_PART_COUNT;
const OrbPart *orb_part(const char *role);

extern const BarPart SONNY_BAR_PARTS[];
extern const int SONNY_BAR_PART_COUNT;

extern const BarField SONNY_BAR_FIELDS[];
extern const int SONNY_BAR_FIELD_COUNT;
const BarField *bar_field(const char *side, const char *role);

/* The colours the health bar runs through, indexed by round(percent * 100).
   The original does not tint its fill: it points a hundred-frame clip at that
   index, and each frame is one flat colour. */
extern const unsigned char SONNY_LIFE_COLOURS[][3];
extern const int SONNY_LIFE_COLOUR_COUNT;

extern const StageChrome SONNY_STAGE_CHROME[];
extern const int SONNY_STAGE_CHROME_COUNT;
const StageChrome *stage_chrome(const char *screen, const char *name);

/* The rows of a layout table that belong to one screen -- or one menu frame
   -- as a run: how many, and where they start. Every table keeps a screen's
   rows together (the generator checks it), so a lookup or a draw loop walks
   that screen's rows rather than the whole table. */
int32_t stage_chrome_rows(const char *screen, int32_t *first);
int32_t clip_part_rows(const char *screen, int32_t *first);
int32_t text_field_rows(const char *screen, int32_t *first);
int32_t button_rows(const char *screen, int32_t *first);
int32_t slot_piece_rows(const char *menu, int32_t *first);
int32_t menu_slot_rows(const char *menu, int32_t *first);

extern const StageLayer SONNY_STAGE_LAYERS[];
extern const int SONNY_STAGE_LAYER_COUNT;
const StageLayer *stage_layer(const char *name);

extern const StageBar SONNY_STAGE_BARS[];
extern const int SONNY_STAGE_BAR_COUNT;
const StageBar *stage_bar(int32_t slot);

extern const StageSlot SONNY_STAGE_SLOTS[];
extern const int SONNY_STAGE_SLOT_COUNT;
const StageSlot *stage_slot(int32_t slot);

extern const DollFrame SONNY_DOLL_FRAMES[];
extern const int SONNY_DOLL_FRAME_COUNT;
extern const DollPart SONNY_DOLL_PARTS[];
extern const int SONNY_DOLL_PART_COUNT;

extern const CastEffect SONNY_CAST_EFFECTS[];
extern const int SONNY_CAST_EFFECT_COUNT;
/* The effect for an animation, or NULL where that animation plays none. */
const CastEffect *cast_effect(const char *animation);

extern const AssetEntry SONNY_ASSETS[];
extern const int SONNY_ASSET_COUNT;

/* What the art this manifest was generated from looked like, written beside
   it as assets/art/stamp.txt. The engine carries the manifest inside itself
   and reads the pictures off the disk, so the two can drift apart -- and a
   picture is not self-describing: art rasterised at two pixels to the stage
   unit drawn by an engine that believes in one comes out at twice its size,
   quietly and everywhere. Comparing the two at startup is how that says so
   rather than simply looking wrong. */
extern const char *const SONNY_ASSET_STAMP;
extern const AssetAnimation SONNY_ANIMATIONS[];
extern const int SONNY_ANIMATION_COUNT;

const AssetEntry *asset_find(const char *name);
const DollPart *doll_part(const char *name);
const AssetAnimation *asset_animation(const char *name);

#endif
'''


# The runs a table's rows make by their first key, worked out the first time
# a screen is asked for. The tables are laid out with each screen's rows
# together, which assert_runs checks here, at generation time.
ROWS_HELPER = r"""/* One screen's run of rows in a table. */
typedef struct {
    const char *key;
    int32_t     first;
    int32_t     count;
} RowRun;

typedef struct {
    RowRun  *runs;
    int32_t  count;
} RowIndex;

static int32_t rows_of(RowIndex *index, const void *rows, size_t stride,
                       int32_t count, size_t key_at, const char *key,
                       int32_t *first)
{
    *first = 0;
    if (!key)
        return 0;
    if (!index->runs && count > 0) {
        index->runs = malloc((size_t)count * sizeof(RowRun));
        if (!index->runs)
            return 0;
        for (int32_t i = 0; i < count; i++) {
            const char *k = *(const char *const *)((const char *)rows
                                                   + (size_t)i * stride
                                                   + key_at);
            RowRun *last = index->count ? &index->runs[index->count - 1]
                                        : NULL;
            if (last && strcmp(last->key, k) == 0) {
                last->count++;
            } else {
                index->runs[index->count].key = k;
                index->runs[index->count].first = i;
                index->runs[index->count].count = 1;
                index->count++;
            }
        }
    }
    for (int32_t i = 0; i < index->count; i++)
        if (strcmp(index->runs[i].key, key) == 0) {
            *first = index->runs[i].first;
            return index->runs[i].count;
        }
    return 0;
}

#define ROWS_OF(table, type, field, count, key, first)                      \
    rows_of(&table##_INDEX, table, sizeof(type), count,                       \
            offsetof(type, field), key, first)
"""


def assert_runs(table, keys):
    """Each key's rows together, which is what lets a lookup take a run."""
    seen = set()
    previous = None
    for key in keys:
        if key != previous and key in seen:
            raise SystemExit('%s: rows for %r are not together' % (table, key))
        seen.add(key)
        previous = key


FIRST_STRING = re.compile(r'\{ "((?:[^"\\]|\\.)*)"')


def check_tables(lines, assets):
    """What the lookups count on: each layout table keeps a screen's rows
    together, and the assets are in the byte order strcmp compares in."""
    for table in ('SONNY_STAGE_CHROME', 'SONNY_CLIP_PARTS',
                  'SONNY_TEXT_FIELDS', 'SONNY_BUTTONS', 'SONNY_SLOT_PIECES',
                  'SONNY_MENU_SLOTS'):
        start = next(i for i, line in enumerate(lines)
                     if line.endswith(' %s[] = {' % table))
        keys = []
        for line in lines[start + 1:]:
            if line.startswith('};'):
                break
            m = FIRST_STRING.search(line)
            if m:
                keys.append(m.group(1))
        assert_runs(table, keys)
    names = [name.encode('utf-8') for name in sorted(assets)]
    if names != sorted(names):
        raise SystemExit('asset names are not in strcmp order')


def c_float(value):
    """A C float literal that round-trips, whatever Python type it came in as."""
    return '%.6ff' % float(value)


def c_string(text):
    out = []
    for ch in str(text):
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 32 or ord(ch) > 126:
            out.extend('\\%03o' % b for b in ch.encode('utf-8'))
        else:
            out.append(ch)
    return '"%s"' % ''.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-i', '--input', default='assets/art/manifest.json')
    ap.add_argument('-o', '--out', default='src/gen')
    ap.add_argument('--doll', default='data/extracted/doll_frames.json')
    ap.add_argument('--doll-parts', default='data/extracted/doll.json')
    ap.add_argument('--stage', default='data/extracted/stage.json')
    ap.add_argument('--cast', default='data/extracted/cast_frames.json')
    args = ap.parse_args()

    with open(args.input, 'rb') as fh:
        raw = fh.read()
    manifest = json.loads(raw.decode('utf-8'))
    assets = manifest['assets']
    stamp = hashlib.sha1(raw).hexdigest()[:16]
    animations = manifest.get('animations') or {}

    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, 'assets_gen.h'), 'w',
              encoding='utf-8') as fh:
        fh.write(HEADER)

    lines = ['/* GENERATED by tools/gen_asset_manifest.py -- do not edit. */',
             '#include <stddef.h>', '#include <stdlib.h>', '#include <string.h>',
             '#include "assets_gen.h"', '', ROWS_HELPER, '']

    for index, (name, entry) in enumerate(sorted(assets.items())):
        lines.append('static const char *const FRAMES_%d[] = { %s };'
                     % (index, ', '.join(c_string(f) for f in entry['frames'])))
        offsets = entry.get('offsets')
        if offsets:
            lines.append('static const AssetOffset OFFSETS_%d[] = { %s };'
                         % (index, ', '.join('{ %s, %s }'
                                             % (c_float(o[0]), c_float(o[1]))
                                             for o in offsets)))
    lines.append('')
    lines.append('const AssetEntry SONNY_ASSETS[] = {')
    for index, (name, entry) in enumerate(sorted(assets.items())):
        b = entry.get('bounds') or [0, 0, 0, 0]
        lines.append('    { %s, %s, FRAMES_%d, %s, %d, %s, %d, %s, %s, %s, %s },'
                     % (c_string(name), c_string(entry['category']), index,
                        ('OFFSETS_%d' % index) if entry.get('offsets')
                        else 'NULL',
                        len(entry['frames']),
                        c_float(entry.get('scale') or 1.0),
                        1 if entry.get('bounds') else 0,
                        c_float(b[0]), c_float(b[1]), c_float(b[2]),
                        c_float(b[3])))
    lines.append('};')
    lines.append('const int SONNY_ASSET_COUNT = '
                 '(int)(sizeof(SONNY_ASSETS) / sizeof(SONNY_ASSETS[0]));')
    lines.append('const char *const SONNY_ASSET_STAMP = %s;' % c_string(stamp))
    lines.append('')
    lines.append('const AssetAnimation SONNY_ANIMATIONS[] = {')
    for name, a in sorted(animations.items(), key=lambda kv: kv[1]['start']):
        lines.append('    { %s, %d, %d, %d },'
                     % (c_string(name), a['start'], a['end'], a['length']))
    lines.append('};')
    lines.append('const int SONNY_ANIMATION_COUNT = '
                 '(int)(sizeof(SONNY_ANIMATIONS) / sizeof(SONNY_ANIMATIONS[0]));')
    # The model's per-frame part transforms, and the part table that says
    # which equipment slot each part draws.
    doll_frames = []
    if os.path.exists(args.doll):
        with open(args.doll, encoding='utf-8') as fh:
            doll_frames = json.load(fh)['frames']
    doll_parts = {}
    if os.path.exists(args.doll_parts):
        with open(args.doll_parts, encoding='utf-8') as fh:
            doll_parts = json.load(fh)

    lines.append('')
    for index, frame in enumerate(doll_frames):
        if not frame:
            continue
        entries = []
        for name, info in sorted(frame.items(), key=lambda kv: kv[1]['depth']):
            m = info['matrix']
            alpha = info.get('alpha')
            entries.append('{ %s, %s, %s, %s, %s, %s, %s, %d, %s }'
                           % (c_string(name), c_float(m[0]), c_float(m[1]),
                              c_float(m[2]), c_float(m[3]), c_float(m[4]),
                              c_float(m[5]), info.get('character') or 0,
                              c_float(1.0 if alpha is None else alpha)))
        lines.append('static const DollPlacement DOLL_%d[] = { %s };'
                     % (index, ', '.join(entries)))
    lines.append('')
    lines.append('const DollFrame SONNY_DOLL_FRAMES[] = {')
    for index, frame in enumerate(doll_frames):
        if frame:
            # Every part of a frame carries the same alpha -- the model is
            # faded as a whole, over the last frames of its death.
            alphas = {round(p.get('alpha', 1.0), 4) for p in frame.values()}
            alpha = min(alphas) if len(alphas) == 1 else 1.0
            lines.append('    { DOLL_%d, %d, %s },'
                         % (index, len(frame), c_float(alpha)))
        else:
            lines.append('    { NULL, 0, 1.0f },')
    lines.append('};')
    lines.append('const int SONNY_DOLL_FRAME_COUNT = '
                 '(int)(sizeof(SONNY_DOLL_FRAMES) / sizeof(SONNY_DOLL_FRAMES[0]));')
    stage = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            stage = json.load(fh).get('slots') or {}
    lines.append('')
    lines.append('const StageSlot SONNY_STAGE_SLOTS[] = {')
    for slot in sorted(stage, key=int):
        s_ = stage[slot]
        lines.append('    { %s, %s, %s, %s, %s, %d },'
                     % (slot, c_float(s_['x']), c_float(s_['y']),
                        c_float(s_['scale_x']), c_float(s_['scale_y']),
                        1 if s_['flip'] else 0))
    lines.append('};')
    lines.append('const int SONNY_STAGE_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_SLOTS) / sizeof(SONNY_STAGE_SLOTS[0]));')
    lines.append('''
const StageSlot *stage_slot(int32_t slot)
{
    for (int i = 0; i < SONNY_STAGE_SLOT_COUNT; i++)
        if (SONNY_STAGE_SLOTS[i].slot == slot)
            return &SONNY_STAGE_SLOTS[i];
    return NULL;
}''')
    bars = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            bars = json.load(fh).get('bars') or {}
    lines.append('')
    lines.append('const StageBar SONNY_STAGE_BARS[] = {')
    for slot in sorted(bars, key=int):
        b_ = bars[slot]
        lines.append('    { %s, %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (slot, c_float(b_['x']), c_float(b_['y']),
                        c_float(b_['scale_x']), c_float(b_['scale_y']),
                        c_float(b_.get('width', 201.0)),
                        c_float(b_.get('height', 28.75)),
                        c_float(b_.get('origin_x', 100.5)),
                        c_float(b_.get('origin_y', 13.95))))
    lines.append('};')
    lines.append('const int SONNY_STAGE_BAR_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_BARS) / sizeof(SONNY_STAGE_BARS[0]));')
    lines.append('''
const StageBar *stage_bar(int32_t slot)
{
    for (int i = 0; i < SONNY_STAGE_BAR_COUNT; i++)
        if (SONNY_STAGE_BARS[i].slot == slot)
            return &SONNY_STAGE_BARS[i];
    return NULL;
}''')
    chrome = []
    layers = {}
    stage_json = {}
    markers_json = {}
    markers_path = os.path.join(os.path.dirname(args.stage), 'markers.json')
    if os.path.exists(markers_path):
        with open(markers_path, encoding='utf-8') as fh:
            markers_json = json.load(fh)
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            stage_json = json.load(fh)
        chrome = stage_json.get('chrome') or []
        layers = stage_json.get('layers') or {}
    lines.append('')
    lines.append('const StageChrome SONNY_STAGE_CHROME[] = {')
    for c in chrome:
        if 'width' not in c:
            continue
        lines.append('    { %s, %s, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (c_string(c['screen']), c_string(c['name']),
                        c['depth'], c['character'],
                        c.get('clip_depth') or 0,
                        c_float(c['x']), c_float(c['y']),
                        c_float(c['scale_x']), c_float(c['scale_y']),
                        c_float(c['width']), c_float(c['height']),
                        c_float(c['origin_x']), c_float(c['origin_y'])))
    lines.append('};')
    lines.append('const int SONNY_STAGE_CHROME_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_CHROME) / sizeof(SONNY_STAGE_CHROME[0]));')
    lines.append("""
static RowIndex SONNY_STAGE_CHROME_INDEX;

int32_t stage_chrome_rows(const char *screen, int32_t *first)
{
    return ROWS_OF(SONNY_STAGE_CHROME, StageChrome, screen,
                   SONNY_STAGE_CHROME_COUNT, screen, first);
}

const StageChrome *stage_chrome(const char *screen, const char *name)
{
    int32_t first, n = stage_chrome_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_STAGE_CHROME[i].name, name) == 0)
            return &SONNY_STAGE_CHROME[i];
    return NULL;
}""")
    speech = stage_json.get('speech') or {}
    chrome_text = stage_json.get('chrome_text') or []

    # The floating number: four sections of one clip, and the pieces a digit
    # and the two words are drawn from.
    numbers = stage_json.get('numbers') or {}

    def number_parts(tag, parts):
        lines.append('static const NumberPart NUMPART_%s[] = {' % tag)
        for part in parts:
            lines.append('    { %s, %s, %s, %s, %s, %s, %d },'
                         % (c_string('#%d' % part['character']),
                            c_float(part['x']), c_float(part['y']),
                            c_float(part.get('scale', 1.0)),
                            c_float(part.get('origin_x') or 0),
                            c_float(part.get('origin_y') or 0),
                            1 if part['name'] == 'KN' else 0))
        lines.append('};')
        return len(parts)

    lines.append('')
    section_sizes = []
    for index, section in enumerate(numbers.get('sections') or []):
        lines.append('static const NumberFrame NUMFRAME_%d[] = {' % index)
        for f in section['frames']:
            lines.append('    { %s, %s, %s },'
                         % (c_float(f['scale']), c_float(f['y']),
                            c_float(f['alpha'])))
        lines.append('};')
        # Only the two word sections carry art of their own; a number's is
        # the digits, so an empty table would just sit there unused.
        part_count = (number_parts('S%d' % index, section['parts'])
                      if section['parts'] else 0)
        section_sizes.append((section['name'], index, len(section['frames']),
                              part_count))
    lines.append('const NumberAnim SONNY_NUMBER_ANIMS[] = {')
    for name, index, frames, part_count in section_sizes:
        lines.append('    { %s, NUMFRAME_%d, %d, %s, %d },'
                     % (c_string(name), index, frames,
                        'NUMPART_S%d' % index if part_count else 'NULL',
                        part_count))
    lines.append('};')
    lines.append('const int SONNY_NUMBER_ANIM_COUNT = '
                 '(int)(sizeof(SONNY_NUMBER_ANIMS) / '
                 'sizeof(SONNY_NUMBER_ANIMS[0]));')
    lines.append(NUMBER_LOOKUP)
    digit_sizes = []
    for digit in (numbers.get('digits') or []):
        digit_sizes.append(number_parts('D%d' % digit['value'],
                                        digit['parts']))
    lines.append('const NumberDigit SONNY_NUMBER_DIGITS[10] = {')
    for value, count in enumerate(digit_sizes):
        lines.append('    { NUMPART_D%d, %d },' % (value, count))
    lines.append('};')
    lines.append('const float SONNY_NUMBER_SPACING = 19.0f;')

    lines.append('')
    lines.append('const ClipPart SONNY_CLIP_PARTS[] = {')
    menu_parts = [dict(part, screen='menu', owner=label)
                  for label, menu in sorted((stage_json.get('menus')
                                             or {}).items())
                  for part in menu['parts']]
    # The pool row is attached rather than placed, so its pieces stay in the
    # row's own coordinates and the screen offsets them per row.
    map_parts = [dict(part, screen='overMap', owner='krinMapper')
                 for part in ((stage_json.get('map_screen') or {})
                              .get('parts') or [])]
    row_parts = [dict(part, screen='menu', owner='talenter')
                 for part in ((stage_json.get('talent_row') or {})
                              .get('parts') or [])]
    for part in ((stage_json.get('clip_parts') or []) + menu_parts + row_parts
                 + map_parts):
        lines.append('    { %s, %s, %s, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (c_string(part['screen']), c_string(part['owner']),
                        c_string(part['name']),
                        part['character'], part['depth'],
                        part.get('frames') or 0,
                        c_float(part['x']), c_float(part['y']),
                        c_float(part['scale_x']), c_float(part['scale_y']),
                        c_float(part.get('width') or 0),
                        c_float(part.get('height') or 0),
                        c_float(part.get('origin_x') or 0),
                        c_float(part.get('origin_y') or 0)))
    lines.append('};')
    lines.append('const int SONNY_CLIP_PART_COUNT = '
                 '(int)(sizeof(SONNY_CLIP_PARTS) / sizeof(SONNY_CLIP_PARTS[0]));')
    lines.append('''
static RowIndex SONNY_CLIP_PARTS_INDEX;

int32_t clip_part_rows(const char *screen, int32_t *first)
{
    return ROWS_OF(SONNY_CLIP_PARTS, ClipPart, screen, SONNY_CLIP_PART_COUNT,
                   screen, first);
}

const ClipPart *clip_part(const char *screen, const char *owner, int32_t index)
{
    int32_t first, n = clip_part_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_CLIP_PARTS[i].owner, owner) == 0 && index-- == 0)
            return &SONNY_CLIP_PARTS[i];
    return NULL;
}''')
    lines.append('')
    lines.append('const TextField SONNY_TEXT_FIELDS[] = {')
    menu_fields = [dict(field, screen='menu', owner=label)
                   for label, menu in sorted((stage_json.get('menus')
                                              or {}).items())
                   for field in menu['fields']]
    for f in chrome_text + menu_fields:
        colour = f.get('color') or [255, 255, 255, 255]
        lines.append('    { %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %d, %d, %d, %d, %d },'
                     % (c_string(f['screen']), c_string(f['owner']),
                        c_string(f['name']),
                        c_string(f.get('variable') or ''),
                        c_string(f.get('text') or ''),
                        c_float(f['x']), c_float(f['y']),
                        c_float(f['width']), c_float(f['height']),
                        c_float(f.get('size') or 10.0),
                        c_float(f.get('leading') or 0.0),
                        f.get('align', 0), 1 if f.get('device') else 0,
                        colour[0], colour[1], colour[2]))
    lines.append('};')
    lines.append('const int SONNY_TEXT_FIELD_COUNT = '
                 '(int)(sizeof(SONNY_TEXT_FIELDS) / sizeof(SONNY_TEXT_FIELDS[0]));')
    lines.append('''
static RowIndex SONNY_TEXT_FIELDS_INDEX;

int32_t text_field_rows(const char *screen, int32_t *first)
{
    return ROWS_OF(SONNY_TEXT_FIELDS, TextField, screen,
                   SONNY_TEXT_FIELD_COUNT, screen, first);
}

const TextField *text_field(const char *screen, const char *owner,
                            int32_t index)
{
    int32_t first, n = text_field_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_TEXT_FIELDS[i].owner, owner) == 0 && index-- == 0)
            return &SONNY_TEXT_FIELDS[i];
    return NULL;
}

const TextField *text_field_var(const char *screen, const char *variable)
{
    int32_t first, n = text_field_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_TEXT_FIELDS[i].variable, variable) == 0)
            return &SONNY_TEXT_FIELDS[i];
    return NULL;
}

const TextField *text_field_named(const char *screen, const char *owner,
                                  const char *name, int32_t occurrence)
{
    int32_t first, n = text_field_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_TEXT_FIELDS[i].owner, owner) == 0
            && strcmp(SONNY_TEXT_FIELDS[i].name, name) == 0
            && occurrence-- == 0)
            return &SONNY_TEXT_FIELDS[i];
    return NULL;
}''')

    ring = stage_json.get('selector') or {}
    lines.append('')
    lines.append('const RingSlot SONNY_RING_SLOTS[] = {')
    for slot in (ring.get('slots') or []):
        lines.append('    { %d, %s, %s, %s, %s },'
                     % (slot['slot'], c_float(slot['x']), c_float(slot['y']),
                        c_float(slot['scale_x']), c_float(slot['scale_y'])))
    lines.append('};')
    lines.append('const int SONNY_RING_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_RING_SLOTS) / sizeof(SONNY_RING_SLOTS[0]));')
    lines.append('const float SONNY_RING_SCALE = %s;'
                 % c_float(ring.get('scale_x') or 1.0))
    lines.append('')
    lines.append('const OrbPart SONNY_ORB_PARTS[] = {')
    for role, part in sorted((ring.get('parts') or {}).items(),
                             key=lambda kv: kv[1]['depth']):
        lines.append('    { %s, %d, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (c_string(role), part['character'], part['depth'],
                        c_float(part['x']), c_float(part['y']),
                        c_float(part['scale_x']), c_float(part['scale_y']),
                        c_float(part.get('width') or 0),
                        c_float(part.get('height') or 0),
                        c_float(part.get('origin_x') or 0),
                        c_float(part.get('origin_y') or 0)))
    lines.append('};')
    lines.append('const int SONNY_ORB_PART_COUNT = '
                 '(int)(sizeof(SONNY_ORB_PARTS) / sizeof(SONNY_ORB_PARTS[0]));')
    lines.append('''
const OrbPart *orb_part(const char *role)
{
    for (int i = 0; i < SONNY_ORB_PART_COUNT; i++)
        if (strcmp(SONNY_ORB_PARTS[i].role, role) == 0)
            return &SONNY_ORB_PARTS[i];
    return NULL;
}''')

    bar = stage_json.get('bar') or {}
    lines.append('')
    lines.append('const BarPart SONNY_BAR_PARTS[] = {')
    for part in (bar.get('graphics') or []):
        if not part.get('width'):
            continue
        lines.append('    { %s, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (c_string(part['name']), part['character'],
                        part['depth'], part.get('clip_depth') or 0,
                        c_float(part['x']), c_float(part['y']),
                        c_float(part['scale_x']), c_float(part['scale_y']),
                        c_float(part['width']), c_float(part['height']),
                        c_float(part['origin_x']), c_float(part['origin_y'])))
    lines.append('};')
    lines.append('const int SONNY_BAR_PART_COUNT = '
                 '(int)(sizeof(SONNY_BAR_PARTS) / sizeof(SONNY_BAR_PARTS[0]));')
    lines.append('')
    lines.append('const BarField SONNY_BAR_FIELDS[] = {')
    for side in ('left', 'right'):
        for f in ((bar.get('text') or {}).get(side) or []):
            colour = f.get('color') or [255, 255, 255, 255]
            lines.append('    { %s, %s, %s, %s, %s, %s, %s, %s, %d, %d, %d, %d, %d },'
                         % (c_string(side), c_string(f['role']),
                            c_float(f['x']), c_float(f['y']),
                            c_float(f['width']), c_float(f['height']),
                            c_float(f.get('size') or 9.0),
                            c_float(f.get('leading') or 0.0),
                            f.get('align', 0),
                            1 if f.get('device') else 0,
                            colour[0], colour[1], colour[2]))
    lines.append('};')
    lines.append('const int SONNY_BAR_FIELD_COUNT = '
                 '(int)(sizeof(SONNY_BAR_FIELDS) / sizeof(SONNY_BAR_FIELDS[0]));')
    lines.append('''
const BarField *bar_field(const char *side, const char *role)
{
    for (int i = 0; i < SONNY_BAR_FIELD_COUNT; i++)
        if (strcmp(SONNY_BAR_FIELDS[i].side, side) == 0
            && strcmp(SONNY_BAR_FIELDS[i].role, role) == 0)
            return &SONNY_BAR_FIELDS[i];
    return NULL;
}''')
    ramp = stage_json.get('life_colours') or []
    lines.append('')
    lines.append('const unsigned char SONNY_LIFE_COLOURS[][3] = {')
    for rgb in ramp:
        lines.append('    { %d, %d, %d },' % tuple(rgb))
    lines.append('};')
    lines.append('const int SONNY_LIFE_COLOUR_COUNT = '
                 '(int)(sizeof(SONNY_LIFE_COLOURS) / sizeof(SONNY_LIFE_COLOURS[0]));')

    lines.append('')
    lines.append('const StageButton SONNY_BUTTONS[] = {')
    # A zone scene's own buttons, keyed by the zone's frame label: the
    # markers that start a fight, and the one that opens that zone's store.
    zone_buttons = [dict(b, screen=label, owner='KrinScreen')
                    for label, group in sorted(((stage_json.get('zone_screen')
                                                 or {}).get('buttons')
                                                or {}).items())
                    for b in group]
    menu_buttons = [dict(b, screen=label)
                    for label, menu in sorted((stage_json.get('menus')
                                               or {}).items())
                    for b in (menu.get('buttons') or [])]
    for b in ((stage_json.get('buttons') or []) + menu_buttons
              + zone_buttons):
        lines.append('    { %s, %s, %s, %d, %s, %s, %s, %s, %s, %s },'
                     % (c_string(b['screen']), c_string(b.get('owner') or ''),
                        c_string(b['name']), b['character'],
                        c_float(b['x']), c_float(b['y']),
                        c_float(b['width']), c_float(b['height']),
                        c_float(b.get('scale_x', 1.0)),
                        c_float(b.get('scale_y', 1.0))))
    lines.append('};')
    lines.append('const int SONNY_BUTTON_COUNT = '
                 '(int)(sizeof(SONNY_BUTTONS) / sizeof(SONNY_BUTTONS[0]));')
    lines.append('''
static RowIndex SONNY_BUTTONS_INDEX;

int32_t button_rows(const char *screen, int32_t *first)
{
    return ROWS_OF(SONNY_BUTTONS, StageButton, screen, SONNY_BUTTON_COUNT,
                   screen, first);
}

const StageButton *stage_button(const char *screen, int32_t character,
                                int32_t index)
{
    int32_t first, n = button_rows(screen, &first);
    for (int32_t i = first; i < first + n; i++)
        if (SONNY_BUTTONS[i].character == character && index-- == 0)
            return &SONNY_BUTTONS[i];
    return NULL;
}''')

    lines.append('')
    lines.append('const ButtonPiece SONNY_BUTTON_ART[] = {')
    for button in sorted((stage_json.get('button_art') or {}),
                         key=lambda k: int(k)):
        for piece in stage_json['button_art'][button]:
            lines.append('    { %d, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                         % (int(button), piece['character'],
                            piece.get('up', 1), piece.get('over', 0),
                            c_float(piece['x']), c_float(piece['y']),
                            c_float(piece['scale_x']),
                            c_float(piece['scale_y']),
                            c_float(piece.get('width') or 0),
                            c_float(piece.get('height') or 0),
                            c_float(piece.get('origin_x') or 0),
                            c_float(piece.get('origin_y') or 0)))
    lines.append('};')
    lines.append('const int SONNY_BUTTON_ART_COUNT = '
                 '(int)(sizeof(SONNY_BUTTON_ART) / sizeof(SONNY_BUTTON_ART[0]));')
    lines.append("""
const ButtonPiece *button_piece(int32_t button, int32_t index)
{
    for (int i = 0; i < SONNY_BUTTON_ART_COUNT; i++)
        if (SONNY_BUTTON_ART[i].button == button && index-- == 0)
            return &SONNY_BUTTON_ART[i];
    return NULL;
}""")

    world = stage_json.get('map_screen') or {}
    lines.append('')
    lines.append('const MapMarker SONNY_MAP_MARKERS[] = {')
    for marker in (world.get('markers') or []):
        lines.append('    { %d, %d, %s, %s, %s, %s },'
                     % (marker['zone'], marker['character'],
                        c_float(marker['x']), c_float(marker['y']),
                        c_float(marker.get('width') or 0),
                        c_float(marker.get('height') or 0)))
    lines.append('};')
    lines.append('const int SONNY_MAP_MARKER_COUNT = '
                 '(int)(sizeof(SONNY_MAP_MARKERS) / '
                 'sizeof(SONNY_MAP_MARKERS[0]));')

    zone_clip = stage_json.get('zone_screen') or {}
    lines.append('')
    lines.append('const ZoneMarker SONNY_ZONE_MARKERS[] = {')
    zoned = markers_json.get('zones') or {}
    for label in sorted((zone_clip.get('labels') or {}),
                        key=lambda k: zone_clip['labels'][k]):
        for marker in zoned.get(label, []):
            lines.append('    { %s, %s, %s, %s, %s, %s },'
                         % (c_string(label), c_string(marker['style']),
                            c_float(marker['x']), c_float(marker['y']),
                            c_float(marker['scale_x']),
                            c_float(marker['scale_y'])))
    lines.append('};')
    lines.append('const int SONNY_ZONE_MARKER_COUNT = '
                 '(int)(sizeof(SONNY_ZONE_MARKERS) / sizeof(SONNY_ZONE_MARKERS[0]));')
    lines.append('''
const ZoneMarker *zone_marker(const char *zone, int32_t index)
{
    for (int i = 0; i < SONNY_ZONE_MARKER_COUNT; i++)
        if (strcmp(SONNY_ZONE_MARKERS[i].zone, zone) == 0 && index-- == 0)
            return &SONNY_ZONE_MARKERS[i];
    return NULL;
}''')
    lines.append('const int SONNY_MARKER_FRAMES = %d;'
                 % (markers_json.get('frames') or 0))
    lines.append('const float SONNY_MARKER_FPS = 30.0f;')
    lines.append('const StageLayer SONNY_ZONE_SCREEN = { "zone", %s, %s, %s, %s };'
                 % (c_float(zone_clip.get('x') or 0),
                    c_float(zone_clip.get('y') or 0),
                    c_float(zone_clip.get('scale_x') or 1),
                    c_float(zone_clip.get('scale_y') or 1)))
    lines.append('const char *const SONNY_ZONE_LABELS[] = {')
    for label in sorted((zone_clip.get('labels') or {}),
                        key=lambda k: zone_clip['labels'][k]):
        lines.append('    %s,' % c_string(label))
    lines.append('};')
    lines.append('const int SONNY_ZONE_LABEL_COUNT = '
                 '(int)(sizeof(SONNY_ZONE_LABELS) / sizeof(SONNY_ZONE_LABELS[0]));')

    lines.append('')
    lines.append('const StageLayer SONNY_STAGE_LAYERS[] = {')
    for name in sorted(layers):
        l_ = layers[name]
        lines.append('    { %s, %s, %s, %s, %s },'
                     % (c_string(name), c_float(l_['x']), c_float(l_['y']),
                        c_float(l_['scale_x']), c_float(l_['scale_y'])))
    lines.append('};')
    lines.append('const int SONNY_STAGE_LAYER_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_LAYERS) / sizeof(SONNY_STAGE_LAYERS[0]));')
    lines.append("""
const StageLayer *stage_layer(const char *name)
{
    for (int i = 0; i < SONNY_STAGE_LAYER_COUNT; i++)
        if (strcmp(SONNY_STAGE_LAYERS[i].name, name) == 0)
            return &SONNY_STAGE_LAYERS[i];
    return NULL;
}""")

    talent_slots = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            talent_slots = json.load(fh).get('talents') or {}
    menus = stage_json.get('menus') or {}
    lines.append('')
    lines.append('const MenuSlot SONNY_MENU_SLOTS[] = {')
    for menu in sorted(menus):
        for name in sorted(menus[menu]['slots']):
            m_ = menus[menu]['slots'][name]
            lines.append('    { %s, %s, %s, %s, %s, %d, %d, %s, %s, %s, %s },'
                         % (c_string(menu), c_string(name),
                            c_float(m_['x']), c_float(m_['y']),
                            c_float(m_['scale']), m_.get('depth') or 0,
                            m_.get('character') or 0,
                            c_float(m_.get('width') or 0),
                            c_float(m_.get('height') or 0),
                            c_float(m_.get('origin_x') or 0),
                            c_float(m_.get('origin_y') or 0)))
    lines.append('};')
    lines.append('const int SONNY_MENU_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_MENU_SLOTS) / sizeof(SONNY_MENU_SLOTS[0]));')
    lines.append('')
    lines.append('const SlotPiece SONNY_SLOT_PIECES[] = {')
    for menu in sorted(menus):
        for name in sorted(menus[menu]['slots']):
            for piece in (menus[menu]['slots'][name].get('pieces') or []):
                lines.append('    { %s, %s, %s, %d, %s, %s, %s, %s, %s, %s, %s, %s },'
                             % (c_string(menu), c_string(name),
                                c_string(piece['name']), piece['character'],
                                c_float(piece['x']), c_float(piece['y']),
                                c_float(piece['scale_x']),
                                c_float(piece['scale_y']),
                                c_float(piece.get('width') or 0),
                                c_float(piece.get('height') or 0),
                                c_float(piece.get('origin_x') or 0),
                                c_float(piece.get('origin_y') or 0)))
    lines.append('};')
    lines.append('const int SONNY_SLOT_PIECE_COUNT = '
                 '(int)(sizeof(SONNY_SLOT_PIECES) / sizeof(SONNY_SLOT_PIECES[0]));')
    lines.append('''
static RowIndex SONNY_SLOT_PIECES_INDEX;
static RowIndex SONNY_MENU_SLOTS_INDEX;

int32_t slot_piece_rows(const char *menu, int32_t *first)
{
    return ROWS_OF(SONNY_SLOT_PIECES, SlotPiece, menu, SONNY_SLOT_PIECE_COUNT,
                   menu, first);
}

int32_t menu_slot_rows(const char *menu, int32_t *first)
{
    return ROWS_OF(SONNY_MENU_SLOTS, MenuSlot, menu, SONNY_MENU_SLOT_COUNT,
                   menu, first);
}

const SlotPiece *slot_piece(const char *menu, const char *slot, int32_t index)
{
    int32_t first, n = slot_piece_rows(menu, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_SLOT_PIECES[i].slot, slot) == 0 && index-- == 0)
            return &SONNY_SLOT_PIECES[i];
    return NULL;
}

const MenuSlot *menu_slot(const char *menu, const char *name)
{
    if (!menu || !name)
        return NULL;
    int32_t first, n = menu_slot_rows(menu, &first);
    for (int32_t i = first; i < first + n; i++)
        if (strcmp(SONNY_MENU_SLOTS[i].name, name) == 0)
            return &SONNY_MENU_SLOTS[i];
    return NULL;
}''')
    lines.append('')
    lines.append('const TalentSlot SONNY_TALENT_SLOTS[] = {')
    for node in sorted(talent_slots, key=int):
        t_ = talent_slots[node]
        lines.append('    { %s, %s, %s, %s },'
                     % (node, c_float(t_['x']), c_float(t_['y']),
                        c_float(t_['scale'])))
    lines.append('};')
    lines.append('const int SONNY_TALENT_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_TALENT_SLOTS) / sizeof(SONNY_TALENT_SLOTS[0]));')
    lines.append('''
const TalentSlot *talent_slot(int32_t node)
{
    for (int i = 0; i < SONNY_TALENT_SLOT_COUNT; i++)
        if (SONNY_TALENT_SLOTS[i].node == node)
            return &SONNY_TALENT_SLOTS[i];
    return NULL;
}''')
    lines.append('')
    lines.append('const DollPart SONNY_DOLL_PARTS[] = {')
    names = doll_parts.get('dollPartsArray') or []
    cores = doll_parts.get('dollPartsCores') or []
    arts = doll_parts.get('dollPartsCores2') or []
    for i, name in enumerate(names):
        lines.append('    { %s, %d, %s },'
                     % (c_string(name), cores[i] if i < len(cores) else 0,
                        c_string(arts[i] if i < len(arts) else '')))
    lines.append('};')
    lines.append('const int SONNY_DOLL_PART_COUNT = '
                 '(int)(sizeof(SONNY_DOLL_PARTS) / sizeof(SONNY_DOLL_PARTS[0]));')

    lines.append('''
const DollPart *doll_part(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_DOLL_PART_COUNT; i++)
        if (strcmp(SONNY_DOLL_PARTS[i].part, name) == 0)
            return &SONNY_DOLL_PARTS[i];
    return NULL;
}''')

    cast = {}
    if os.path.exists(args.cast):
        with open(args.cast, encoding='utf-8') as fh:
            cast = json.load(fh)
    lines.append('')
    for animation in sorted(cast):
        for index, frame in enumerate(cast[animation]['frames']):
            if not frame:
                continue
            entries = []
            for layer in frame:
                m = layer['matrix']
                entries.append('{ %d, %s, %s, %s, %s, %s, %s, %s, %d }'
                               % (layer['character'], c_float(m[0]),
                                  c_float(m[1]), c_float(m[2]), c_float(m[3]),
                                  c_float(m[4]), c_float(m[5]),
                                  c_float(layer['alpha']), layer['tinted']))
            lines.append('static const CastLayer CAST_%s_%d[] = { %s };'
                         % (animation.upper(), index, ', '.join(entries)))
    for animation in sorted(cast):
        lines.append('static const CastFrame CAST_%s[] = {'
                     % animation.upper())
        for index, frame in enumerate(cast[animation]['frames']):
            if frame:
                lines.append('    { CAST_%s_%d, %d },'
                             % (animation.upper(), index, len(frame)))
            else:
                lines.append('    { NULL, 0 },')
        lines.append('};')
    lines.append('const CastEffect SONNY_CAST_EFFECTS[] = {')
    for animation in sorted(cast):
        lines.append('    { %s, %d, CAST_%s, %d, %d },'
                     % (c_string(animation), cast[animation]['character'],
                        animation.upper(), len(cast[animation]['frames']),
                        cast[animation].get('loops', 0)))
    lines.append('};')
    lines.append('const int SONNY_CAST_EFFECT_COUNT = '
                 '(int)(sizeof(SONNY_CAST_EFFECTS) '
                 '/ sizeof(SONNY_CAST_EFFECTS[0]));')
    lines.append('''
const CastEffect *cast_effect(const char *animation)
{
    if (!animation)
        return NULL;
    for (int i = 0; i < SONNY_CAST_EFFECT_COUNT; i++)
        if (strcmp(SONNY_CAST_EFFECTS[i].animation, animation) == 0)
            return &SONNY_CAST_EFFECTS[i];
    return NULL;
}

/* The assets are written out in strcmp order, so a name is a binary search
   away -- it is asked for once for every picture on every frame. */
const AssetEntry *asset_find(const char *name)
{
    if (!name)
        return NULL;
    int lo = 0, hi = SONNY_ASSET_COUNT - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        int order = strcmp(SONNY_ASSETS[mid].name, name);
        if (order == 0)
            return &SONNY_ASSETS[mid];
        if (order < 0)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return NULL;
}

const AssetAnimation *asset_animation(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_ANIMATION_COUNT; i++)
        if (strcmp(SONNY_ANIMATIONS[i].name, name) == 0)
            return &SONNY_ANIMATIONS[i];
    return NULL;
}''')

    check_tables(lines, assets)
    with open(os.path.join(args.out, 'assets_gen.c'), 'w',
              encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    # And the same stamp beside the art, for the engine to check its own
    # manifest against at startup.
    with open(os.path.join(os.path.dirname(args.input), 'stamp.txt'), 'w',
              encoding='utf-8') as fh:
        fh.write(stamp + '\n')

    print('%d assets, %d animations, %d doll frames, %d parts -> %s (%s)'
          % (len(assets), len(animations), len(doll_frames),
             len(doll_parts.get('dollPartsArray') or []), args.out, stamp))


if __name__ == '__main__':
    main()
