#!/usr/bin/env python3
"""Compile assets/art/manifest.json into C tables.

Same reasoning as the game data: generating C keeps a parser out of the
runtime and makes the asset set visible in a diff.

    python3 tools/gen_asset_manifest.py
"""
import argparse
import json
import os

HEADER = '''/* GENERATED by tools/gen_asset_manifest.py -- do not edit. */
#ifndef SONNY_ASSETS_GEN_H
#define SONNY_ASSETS_GEN_H

#include <stdint.h>

/* One named asset: a still has a single frame, an animation has several, in
   order. Paths are relative to the repository root. */
/* Where a frame's own origin sits inside its exported image. Drawing the
   image with its top-left at (target - offset) puts the art exactly where the
   game draws it; without this, trimmed and padded exports land beside their
   mark. */
typedef struct {
    float x, y;
} AssetOffset;

typedef struct {
    const char        *name;
    const char        *category;
    const char *const *frames;
    const AssetOffset *offsets;   /* NULL when unknown */
    int32_t            frame_count;
    /* Where this art sits relative to its parent's origin, when known: the
       shape's bounds with its placement matrix applied. has_bounds is 0 for
       assets whose position the engine supplies instead. */
    int32_t            has_bounds;
    float              xmin, ymin, xmax, ymax;
} AssetEntry;

/* An animation state of the character model, as its frame labels define it.
   Frames are 1-based indices into the model's own frame list. */
typedef struct {
    const char *name;
    int32_t     start;
    int32_t     end;
    int32_t     length;
} AssetAnimation;

/* One part of the character model on one frame: the instance name and the
   matrix the model's timeline gives it. Matrices are SWF form --
   x' = a*x + c*y + tx, y' = b*x + d*y + ty -- with translation in pixels. */
typedef struct {
    const char *part;
    float       a, b, c, d, tx, ty;
} DollPlacement;

typedef struct {
    const DollPlacement *parts;
    int32_t              count;
} DollFrame;

/* How a doll part maps to equipment: `core` indexes the 7 equipment slots and
   `art` is the name used in the export ("M_<art>_<look>"). */
typedef struct {
    const char *part;
    int32_t     core;
    const char *art;
} DollPart;

/* Where the battle screen stands each unit, in stage coordinates, straight
   out of the original's own display list. The right-hand team's containers
   carry a negative horizontal scale, which is how the game mirrors them. */
typedef struct {
    int32_t slot;
    float   x, y;
    float   scale_x, scale_y;
    int32_t flip;
} StageSlot;

/* Where the health and focus bar for a slot sits, straight off the root
   timeline (p1BAR..p6BAR), with the bar art's own size. */
typedef struct {
    int32_t slot;
    float   x, y;          /* where the bar is placed */
    float   scale;
    float   width, height; /* the bar art's size */
    float   origin_x, origin_y;  /* where its own origin sits inside it */
} StageBar;

/* Where a talent tree node sits on the stage. */
typedef struct {
    int32_t node;
    float   x, y;
    float   scale;
} TalentSlot;

/* A named slot on one of the menu screens, in stage coordinates: the 36 bag
   slots, the 7 equipment slots, the 15 drop slots, and the doll preview. */
typedef struct {
    const char *name;
    float       x, y;
    float       scale;
} MenuSlot;

extern const MenuSlot SONNY_MENU_SLOTS[];
extern const int SONNY_MENU_SLOT_COUNT;
const MenuSlot *menu_slot(const char *name);

extern const TalentSlot SONNY_TALENT_SLOTS[];
extern const int SONNY_TALENT_SLOT_COUNT;
const TalentSlot *talent_slot(int32_t node);

extern const StageBar SONNY_STAGE_BARS[];
extern const int SONNY_STAGE_BAR_COUNT;
const StageBar *stage_bar(int32_t slot);

extern const StageSlot SONNY_STAGE_SLOTS[];
extern const int SONNY_STAGE_SLOT_COUNT;
const StageSlot *stage_slot(int32_t slot);

extern const DollFrame SONNY_DOLL_FRAMES[];
extern const int SONNY_DOLL_FRAME_COUNT;
extern const DollPart SONNY_DOLL_PARTS[];
extern const int SONNY_DOLL_PART_COUNT;

extern const AssetEntry SONNY_ASSETS[];
extern const int SONNY_ASSET_COUNT;
extern const AssetAnimation SONNY_ANIMATIONS[];
extern const int SONNY_ANIMATION_COUNT;

const AssetEntry *asset_find(const char *name);
const DollPart *doll_part(const char *name);
const AssetAnimation *asset_animation(const char *name);

#endif
'''


def c_float(value):
    """A C float literal that round-trips, whatever Python type it came in as."""
    return '%.6ff' % float(value)


def c_string(text):
    out = []
    for ch in str(text):
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 32 or ord(ch) > 126:
            out.extend('\\%03o' % b for b in ch.encode('utf-8'))
        else:
            out.append(ch)
    return '"%s"' % ''.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-i', '--input', default='assets/art/manifest.json')
    ap.add_argument('-o', '--out', default='src/gen')
    ap.add_argument('--doll', default='data/extracted/doll_frames.json')
    ap.add_argument('--doll-parts', default='data/extracted/doll.json')
    ap.add_argument('--stage', default='data/extracted/stage.json')
    args = ap.parse_args()

    with open(args.input, encoding='utf-8') as fh:
        manifest = json.load(fh)
    assets = manifest['assets']
    animations = manifest.get('animations') or {}

    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, 'assets_gen.h'), 'w',
              encoding='utf-8') as fh:
        fh.write(HEADER)

    lines = ['/* GENERATED by tools/gen_asset_manifest.py -- do not edit. */',
             '#include <stddef.h>', '#include <string.h>',
             '#include "assets_gen.h"', '']

    for index, (name, entry) in enumerate(sorted(assets.items())):
        lines.append('static const char *const FRAMES_%d[] = { %s };'
                     % (index, ', '.join(c_string(f) for f in entry['frames'])))
        offsets = entry.get('offsets')
        if offsets:
            lines.append('static const AssetOffset OFFSETS_%d[] = { %s };'
                         % (index, ', '.join('{ %s, %s }'
                                             % (c_float(o[0]), c_float(o[1]))
                                             for o in offsets)))
    lines.append('')
    lines.append('const AssetEntry SONNY_ASSETS[] = {')
    for index, (name, entry) in enumerate(sorted(assets.items())):
        b = entry.get('bounds') or [0, 0, 0, 0]
        lines.append('    { %s, %s, FRAMES_%d, %s, %d, %d, %s, %s, %s, %s },'
                     % (c_string(name), c_string(entry['category']), index,
                        ('OFFSETS_%d' % index) if entry.get('offsets')
                        else 'NULL',
                        len(entry['frames']),
                        1 if entry.get('bounds') else 0,
                        c_float(b[0]), c_float(b[1]), c_float(b[2]),
                        c_float(b[3])))
    lines.append('};')
    lines.append('const int SONNY_ASSET_COUNT = '
                 '(int)(sizeof(SONNY_ASSETS) / sizeof(SONNY_ASSETS[0]));')
    lines.append('')
    lines.append('const AssetAnimation SONNY_ANIMATIONS[] = {')
    for name, a in sorted(animations.items(), key=lambda kv: kv[1]['start']):
        lines.append('    { %s, %d, %d, %d },'
                     % (c_string(name), a['start'], a['end'], a['length']))
    lines.append('};')
    lines.append('const int SONNY_ANIMATION_COUNT = '
                 '(int)(sizeof(SONNY_ANIMATIONS) / sizeof(SONNY_ANIMATIONS[0]));')
    # The model's per-frame part transforms, and the part table that says
    # which equipment slot each part draws.
    doll_frames = []
    if os.path.exists(args.doll):
        with open(args.doll, encoding='utf-8') as fh:
            doll_frames = json.load(fh)['frames']
    doll_parts = {}
    if os.path.exists(args.doll_parts):
        with open(args.doll_parts, encoding='utf-8') as fh:
            doll_parts = json.load(fh)

    lines.append('')
    for index, frame in enumerate(doll_frames):
        if not frame:
            continue
        entries = []
        for name, info in sorted(frame.items(), key=lambda kv: kv[1]['depth']):
            m = info['matrix']
            entries.append('{ %s, %s, %s, %s, %s, %s, %s }'
                           % (c_string(name), c_float(m[0]), c_float(m[1]),
                              c_float(m[2]), c_float(m[3]), c_float(m[4]),
                              c_float(m[5])))
        lines.append('static const DollPlacement DOLL_%d[] = { %s };'
                     % (index, ', '.join(entries)))
    lines.append('')
    lines.append('const DollFrame SONNY_DOLL_FRAMES[] = {')
    for index, frame in enumerate(doll_frames):
        if frame:
            lines.append('    { DOLL_%d, %d },' % (index, len(frame)))
        else:
            lines.append('    { NULL, 0 },')
    lines.append('};')
    lines.append('const int SONNY_DOLL_FRAME_COUNT = '
                 '(int)(sizeof(SONNY_DOLL_FRAMES) / sizeof(SONNY_DOLL_FRAMES[0]));')
    stage = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            stage = json.load(fh).get('slots') or {}
    lines.append('')
    lines.append('const StageSlot SONNY_STAGE_SLOTS[] = {')
    for slot in sorted(stage, key=int):
        s_ = stage[slot]
        lines.append('    { %s, %s, %s, %s, %s, %d },'
                     % (slot, c_float(s_['x']), c_float(s_['y']),
                        c_float(s_['scale_x']), c_float(s_['scale_y']),
                        1 if s_['flip'] else 0))
    lines.append('};')
    lines.append('const int SONNY_STAGE_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_SLOTS) / sizeof(SONNY_STAGE_SLOTS[0]));')
    lines.append('''
const StageSlot *stage_slot(int32_t slot)
{
    for (int i = 0; i < SONNY_STAGE_SLOT_COUNT; i++)
        if (SONNY_STAGE_SLOTS[i].slot == slot)
            return &SONNY_STAGE_SLOTS[i];
    return NULL;
}''')
    bars = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            bars = json.load(fh).get('bars') or {}
    lines.append('')
    lines.append('const StageBar SONNY_STAGE_BARS[] = {')
    for slot in sorted(bars, key=int):
        b_ = bars[slot]
        lines.append('    { %s, %s, %s, %s, %s, %s, %s, %s },'
                     % (slot, c_float(b_['x']), c_float(b_['y']),
                        c_float(b_['scale_x']),
                        c_float(b_.get('width', 201.0)),
                        c_float(b_.get('height', 28.75)),
                        c_float(b_.get('origin_x', 100.5)),
                        c_float(b_.get('origin_y', 13.95))))
    lines.append('};')
    lines.append('const int SONNY_STAGE_BAR_COUNT = '
                 '(int)(sizeof(SONNY_STAGE_BARS) / sizeof(SONNY_STAGE_BARS[0]));')
    lines.append('''
const StageBar *stage_bar(int32_t slot)
{
    for (int i = 0; i < SONNY_STAGE_BAR_COUNT; i++)
        if (SONNY_STAGE_BARS[i].slot == slot)
            return &SONNY_STAGE_BARS[i];
    return NULL;
}''')
    talent_slots = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            talent_slots = json.load(fh).get('talents') or {}
    menu_slots = {}
    if os.path.exists(args.stage):
        with open(args.stage, encoding='utf-8') as fh:
            stage_data = json.load(fh)
        # The character screen carries the slots; the victory screen adds the
        # drop slots on top of the same layout.
        for label in ('character', 'victory'):
            menu_slots.update((stage_data.get('menu') or {}).get(label) or {})
    lines.append('')
    lines.append('const MenuSlot SONNY_MENU_SLOTS[] = {')
    for name in sorted(menu_slots):
        m_ = menu_slots[name]
        lines.append('    { %s, %s, %s, %s },'
                     % (c_string(name), c_float(m_['x']), c_float(m_['y']),
                        c_float(m_['scale'])))
    lines.append('};')
    lines.append('const int SONNY_MENU_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_MENU_SLOTS) / sizeof(SONNY_MENU_SLOTS[0]));')
    lines.append('''
const MenuSlot *menu_slot(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_MENU_SLOT_COUNT; i++)
        if (strcmp(SONNY_MENU_SLOTS[i].name, name) == 0)
            return &SONNY_MENU_SLOTS[i];
    return NULL;
}''')
    lines.append('')
    lines.append('const TalentSlot SONNY_TALENT_SLOTS[] = {')
    for node in sorted(talent_slots, key=int):
        t_ = talent_slots[node]
        lines.append('    { %s, %s, %s, %s },'
                     % (node, c_float(t_['x']), c_float(t_['y']),
                        c_float(t_['scale'])))
    lines.append('};')
    lines.append('const int SONNY_TALENT_SLOT_COUNT = '
                 '(int)(sizeof(SONNY_TALENT_SLOTS) / sizeof(SONNY_TALENT_SLOTS[0]));')
    lines.append('''
const TalentSlot *talent_slot(int32_t node)
{
    for (int i = 0; i < SONNY_TALENT_SLOT_COUNT; i++)
        if (SONNY_TALENT_SLOTS[i].node == node)
            return &SONNY_TALENT_SLOTS[i];
    return NULL;
}''')
    lines.append('')
    lines.append('const DollPart SONNY_DOLL_PARTS[] = {')
    names = doll_parts.get('dollPartsArray') or []
    cores = doll_parts.get('dollPartsCores') or []
    arts = doll_parts.get('dollPartsCores2') or []
    for i, name in enumerate(names):
        lines.append('    { %s, %d, %s },'
                     % (c_string(name), cores[i] if i < len(cores) else 0,
                        c_string(arts[i] if i < len(arts) else '')))
    lines.append('};')
    lines.append('const int SONNY_DOLL_PART_COUNT = '
                 '(int)(sizeof(SONNY_DOLL_PARTS) / sizeof(SONNY_DOLL_PARTS[0]));')

    lines.append('''
const DollPart *doll_part(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_DOLL_PART_COUNT; i++)
        if (strcmp(SONNY_DOLL_PARTS[i].part, name) == 0)
            return &SONNY_DOLL_PARTS[i];
    return NULL;
}

const AssetEntry *asset_find(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_ASSET_COUNT; i++)
        if (strcmp(SONNY_ASSETS[i].name, name) == 0)
            return &SONNY_ASSETS[i];
    return NULL;
}

const AssetAnimation *asset_animation(const char *name)
{
    if (!name)
        return NULL;
    for (int i = 0; i < SONNY_ANIMATION_COUNT; i++)
        if (strcmp(SONNY_ANIMATIONS[i].name, name) == 0)
            return &SONNY_ANIMATIONS[i];
    return NULL;
}''')

    with open(os.path.join(args.out, 'assets_gen.c'), 'w',
              encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    print('%d assets, %d animations, %d doll frames, %d parts -> %s'
          % (len(assets), len(animations), len(doll_frames),
             len(doll_parts.get('dollPartsArray') or []), args.out))


if __name__ == '__main__':
    main()
