#!/usr/bin/env python3
"""Reference transcription of the character stat pipeline and the reward
formulas, from DefineSprite_1503 (the character screen), frame 196 (battle
setup), frame 212 (enemy rating) and expWorkOut in frame 62.

    python3 tools/ref_character.py > tests/vectors_character.txt
"""
import json
import math
import random
import sys

ELEMENTS = 8


def stat_sets(equip, spent, items):
    stat = list(spent)
    per = [0.0] * ELEMENTS
    deff = [0.0] * ELEMENTS
    for item_id in equip:
        it = items.get(item_id)
        if it is None:
            continue
        for i in range(5):
            stat[i] += it['statUpdater'][i]
        for e in range(ELEMENTS):
            per[e] += it['statUpdaterP'][e]
            deff[e] += it['statUpdaterD'][e]
    return stat, per, deff


def derive(level, equip, spent, cls, items):
    stat, per, deff = stat_sets(equip, spent, items)
    life = stat[0] + math.ceil(cls['vitality'] + cls['vitality_growth'] * level)
    strength = stat[1] + math.ceil(cls['strength'] + cls['strength_growth'] * level)
    magic = stat[2] + math.ceil(cls['magic'] + cls['magic_growth'] * level)
    speed = stat[3] + math.ceil(cls['speed'] + cls['speed_growth'] * level)
    focus = stat[4] + math.ceil(cls['focus'])
    baseline = math.ceil(25 + 5 * level)
    return (life, strength, magic, speed, focus,
            [per[e] + baseline for e in range(ELEMENTS)],
            [deff[e] + baseline for e in range(ELEMENTS)])


def enemy_rating(levels):
    total, scale = 0, 1
    for lv in levels:
        total += lv
        scale += 0.2
    return total / len(levels) * scale


def xp_gain(rating, player_level):
    diff = 1 + (rating - player_level) * 0.15
    diff = max(0, min(3, diff))
    return diff * (100 / (1 + player_level ** (0.6 + 0.3 * (player_level / 100))))


def main():
    items = {it['id']: it for it in json.load(open('data/extracted/items.json'))}
    units = {u['id']: u for u in json.load(open('data/extracted/units.json'))}
    # Krin.ClassStats[0] = Krin.Class + 1, so the four player classes are unit
    # templates 1..4. Names are not unique -- there are two Templars -- so the
    # id is what identifies a class.
    classes = [1, 2, 3, 4]

    rnd = random.Random(777)
    print('# generated by tools/ref_character.py -- do not edit')
    print('# CHAR class_id level spent0..4 equip0..6 EXPECT life strength '
          'magic speed focus per0 def0')
    for _ in range(300):
        cls_id = rnd.choice(classes)
        cls = units[cls_id]
        level = rnd.randint(1, 40)
        spent = [rnd.randint(0, 20) for _ in range(5)]
        equip = [rnd.choice(list(items)) if rnd.random() < 0.7 else 0
                 for _ in range(7)]
        life, strength, magic, speed, focus, per, deff = derive(
            level, equip, spent, cls, items)
        print('CHAR %d %d %s %s EXPECT %g %g %g %g %g %g %g'
              % (cls_id, level, ' '.join(str(x) for x in spent),
                 ' '.join(str(x) for x in equip),
                 life, strength, magic, speed, focus, per[0], deff[0]))

    print('# XP rating player_level EXPECT gain')
    for _ in range(200):
        levels = [rnd.randint(1, 40) for _ in range(rnd.randint(1, 3))]
        rating = enemy_rating(levels)
        player_level = rnd.randint(1, 40)
        print('XP %.17g %d EXPECT %.17g'
              % (rating, player_level, xp_gain(rating, player_level)))

    print('# RATING count levels... EXPECT rating')
    for _ in range(100):
        levels = [rnd.randint(1, 40) for _ in range(rnd.randint(1, 3))]
        print('RATING %d %s EXPECT %.17g'
              % (len(levels), ' '.join(str(x) for x in levels),
                 enemy_rating(levels)))


if __name__ == '__main__':
    sys.exit(main())
