#!/usr/bin/env python3
"""Reference transcription of Sonny's damage math, straight from the
decompiled executeMove()/perScript(), used to generate test vectors for the C
port. Kept deliberately literal -- it mirrors the ActionScript statement by
statement, including the shield comparison's exact boundary behaviour.

    python3 tools/ref_formula.py > tests/vectors_formula.txt
"""
import math
import random
import sys


def percalk(c, element):
    return (c['PERU'][element] + c['SPEEDU'] / 2) / (25 + 5 * c['plevel']) * 25


def defcalk(c, t, element):
    d = (t['DEFU'][element] / (25 + 5 * t['plevel']) * 25
         - (c['plevel'] - t['plevel']) * 3)
    return 1 if d <= 0 else d


def full_damage(c, t, a, roll):
    P = percalk(c, a['element'])
    D = defcalk(c, t, a['element'])
    raw = ((c['STRENGTHU'] + a['strength_add']) * a['strength_coef']
           + (c['MAGICU'] + a['magic_add']) * a['magic_coef']
           + (c['SPEEDU'] + a['speed_add']) * a['speed_coef']
           + c['FOCUSN'] * a['focus_coef']
           + a['flat_damage'] + c['DMG'] + t['IDMG'])
    pierced = roll < (P + a['hit_add']) * a['hit_coef'] / D * 15
    if pierced:
        mit = 1 - (D - P) / 100
    else:
        mit = 1 - D * (1 - P / 200) / 100
    if mit < 0:
        mit = 0
    final = math.ceil(raw * a['damage_coef'] * mit
                      * (1 + c['DMG2']) * (1 + t['IDMG2']))
    if final <= 0:
        final = 1
    return P, D, pierced, final


def apply_damage(t, damage):
    before = t['LIFEN']
    difference = (t['SHIELD'] - damage) if t['SHIELD'] > 0 else 0
    if difference > 0:
        t['SHIELD'] -= damage
        absorbed = damage
    else:
        absorbed = t['SHIELD']
        damage -= t['SHIELD']
        t['SHIELD'] = 0
        if t['SSWITCH'] == 0:
            t['LIFEN'] -= damage
            if t['LIFEN'] <= 0:
                t['LIFEN'] = 0
                t['FOCUSN'] = 0
        else:
            t['LIFEN'] += damage
            if t['LIFEN'] > t['LIFEU']:
                t['LIFEN'] = t['LIFEU']
    return before - t['LIFEN'], absorbed


def main():
    rnd = random.Random(20260912)
    print('# generated by tools/ref_formula.py -- do not edit')
    print('# caster: plevel STRENGTHU MAGICU SPEEDU FOCUSN PERU DMG DMG2')
    print('# target: plevel DEFU IDMG IDMG2 LIFEN LIFEU SHIELD SSWITCH')
    print('# ability: element str_add str_coef mag_add mag_coef spd_add '
          'spd_coef hit_add hit_coef flat dmg_coef focus_coef')
    print('# roll -> expect: pierced damage life_lost absorbed life_after '
          'shield_after focus_after')
    for _ in range(400):
        c = {
            'plevel': rnd.randint(1, 30),
            'STRENGTHU': round(rnd.uniform(1, 400), 2),
            'MAGICU': round(rnd.uniform(0, 400), 2),
            'SPEEDU': round(rnd.uniform(1, 300), 2),
            'FOCUSN': rnd.randint(0, 300),
            'PERU': [round(rnd.uniform(0, 120), 2)] * 8,
            'DMG': round(rnd.uniform(0, 50), 2),
            'DMG2': round(rnd.choice([0, 0, 0.1, 0.25, 0.5]), 2),
        }
        t = {
            'plevel': rnd.randint(1, 30),
            'DEFU': [round(rnd.uniform(0, 200), 2)] * 8,
            'IDMG': round(rnd.choice([0, 0, 10, 100]), 2),
            'IDMG2': round(rnd.choice([0, 0, 0.2, -0.3]), 2),
            'LIFEN': rnd.randint(1, 2000),
            'LIFEU': 2000,
            'SHIELD': rnd.choice([0, 0, 0, 50, 500]),
            'SSWITCH': rnd.choice([0, 0, 0, 1]),
            'FOCUSN': rnd.randint(0, 300),
        }
        a = {
            'element': rnd.randrange(8),
            'strength_add': rnd.choice([0, 0, 5, 20]),
            'strength_coef': rnd.choice([0, 1, 1.6, 2.5]),
            'magic_add': rnd.choice([0, 0, 5]),
            'magic_coef': rnd.choice([0, 0, 1, 1.8]),
            'speed_add': rnd.choice([0, 0, 3]),
            'speed_coef': rnd.choice([0, 0, 0.5]),
            'hit_add': rnd.choice([0, 0, 10, -5]),
            'hit_coef': rnd.choice([1, 1, 1.5, 0.5]),
            'flat_damage': rnd.choice([0, 5, 30]),
            'damage_coef': rnd.choice([1, 1, 1.25]),
            'focus_coef': rnd.choice([0, 0, 0.5]),
        }
        roll = rnd.randrange(100)

        P, D, pierced, damage = full_damage(c, t, a, roll)
        snapshot = dict(t)
        lost, absorbed = apply_damage(snapshot, damage)

        print(' '.join(str(x) for x in [
            c['plevel'], c['STRENGTHU'], c['MAGICU'], c['SPEEDU'], c['FOCUSN'],
            c['PERU'][0], c['DMG'], c['DMG2'],
            t['plevel'], t['DEFU'][0], t['IDMG'], t['IDMG2'], t['LIFEN'],
            t['LIFEU'], t['SHIELD'], t['SSWITCH'], t['FOCUSN'],
            a['element'], a['strength_add'], a['strength_coef'], a['magic_add'],
            a['magic_coef'], a['speed_add'], a['speed_coef'], a['hit_add'],
            a['hit_coef'], a['flat_damage'], a['damage_coef'], a['focus_coef'],
            roll,
            int(pierced), damage, lost, absorbed, snapshot['LIFEN'],
            snapshot['SHIELD'], snapshot['FOCUSN'],
        ]))


if __name__ == '__main__':
    sys.exit(main())
